App\Entity\Localidade\Cidade:
    type: entity
    table: localidade.cidade
    indexes:
        IDX_F8EE741B9F5A440B:
            columns:
                - estado_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nome:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToOne:
        estado:
            targetEntity: App\Entity\Localidade\Estado
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                estado_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
