App\Entity\Localidade\Pais:
    type: entity
    table: localidade.pais
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nome:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        sigla:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
    lifecycleCallbacks: {  }
