parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        types:
            point:
                class:                App\DBAL\Type\Spatial\Geometry\PointType
                commented:            true
        connections:
            default:
                driver:   '%env(resolve:VOGEL_DRIVER)%'
                host:     '%env(resolve:VOGEL_HOST)%'
                port:     '%env(resolve:VOGEL_PORT)%'
                dbname:   '%env(resolve:VOGEL_DBNAME)%'
                user:     '%env(resolve:VOGEL_USER)%'
                password: '%env(resolve:VOGEL_PASSWORD)%'
                charset:  '%env(resolve:VOGEL_CHARSET)%'
                mapping_types:
                    point: point
                schema_filter: '/^(nutri.)/'
            localidade:
                driver:   '%env(resolve:VOGEL_DRIVER)%'
                host:     '%env(resolve:VOGEL_HOST)%'
                port:     '%env(resolve:VOGEL_PORT)%'
                dbname:   '%env(resolve:VOGEL_DBNAME)%'
                user:     '%env(resolve:VOGEL_USER)%'
                password: '%env(resolve:VOGEL_PASSWORD)%'
                charset:  '%env(resolve:VOGEL_CHARSET)%'
                mapping_types:
                    point: point
                schema_filter: '/^(localidade.)/'
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    Nutri:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/doctrine/nutri'
                        prefix: 'App\Entity\Nutri'
                        alias: App\Entity\Nutri
                    Localidade:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/doctrine/localidade'
                        prefix: 'App\Entity\Localidade'
                        alias: App\Entity\Localidade
            localidade:
                connection: localidade
                mappings:
                    Localidade:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/doctrine/localidade'
                        prefix: 'App\Entity\Localidade'
                        alias: App\Entity\Localidade
                        